=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-attestation/2022-11/schame-online.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "EBSI Verifiable Attestation",
    "description": "Schema of an EBSI Verifiable Attestation",
    "type": "object",
    "properties": {
        "@context": {
            "description": "Defines semantic context of the Verifiable Attestation",
            "type": "array",
            "items": {
                "type": "string",
                "format": "uri"
            }
        },
        "id": {
            "description": "Defines unique identifier of the Verifiable Attestation",
            "type": "string",
            "format": "uri"
        },
        "type": {
            "description": "Defines the Verifiable Credential type",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "issuer": {
            "description": "Defines the issuer of the Verifiable Attestation",
            "type": "string",
            "format": "uri"
        },
        "issuanceDate": {
            "description": "Defines the date and time, when the Verifiable Attestation becomes valid",
            "type": "string",
            "format": "date-time"
        },
        "issued": {
            "description": "Defines when the Verifiable Attestation was issued",
            "type": "string",
            "format": "date-time"
        },
        "validFrom": {
            "description": "Defines the date and time, when the Verifiable Attestation becomes valid",
            "type": "string",
            "format": "date-time"
        },
        "validUntil": {
            "description": "Defines the date and time, when the Verifiable Attestation expires",
            "type": "string",
            "format": "date-time"
        },
        "expirationDate": {
            "description": "Defines the date and time, when the Verifiable Attestation expires",
            "type": "string",
            "format": "date-time"
        },
        "credentialSubject": {
            "description": "Defines information about the subject that is described by the Verifiable Attestation",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Defines the DID of the subject that is described by the Verifiable Attestation",
                    "type": "string",
                    "format": "uri"
                }
            }
        },
        "credentialStatus": {
            "description": "Contains information about how to verify the status of the Verifiable Attestation (via the Revocation and Endorsement Registry, RER)",
            "type": "object",
            "properties": {
                "id": {
                    "description": "References record in the Revocation and Endorsement Registry (RER) to enable verification of a Verifiable Attestationâ€™s validity",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines the Verifiable Credential status type",
                    "type": "string"
                },
                "statusPurpose": {
                    "description": "Purpose of the status entry",
                    "type": "string",
                    "enum": [
                        "revocation",
                        "suspension"
                    ]
                },
                "statusListIndex": {
                    "description": "Integer expressed as a string. The zero based index value identifies the bit position of the status",
                    "type": "string"
                },
                "statusListCredential": {
                    "description": "URL referencing the StatusList2021Credential",
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "id",
                "type"
            ]
        },
        "credentialSchema": {
            "description": "Contains information about the credential schema (template) on which the Verifiable Authorisation is based",
            "type": "object",
            "properties": {
                "id": {
                    "description": "References the credential schema (template) stored on the (relevant) Trusted Schemas Registry (TSR) on which the Verifiable Authorisation is based",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines credential schema type",
                    "type": "string",
                    "enum": [
                        "FullJsonSchemaValidator2021"
                    ]
                }
            },
            "required": [
                "id",
                "type"
            ]
        },
        "evidence": {
            "description": "Contains information about the process which resulted in the issuance of the Verifiable Attestation",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
                        "type": "string"
                    },
                    "type": {
                        "description": "Defines the evidence type",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "id",
                    "type"
                ]
            }
        },
        "proof": {
            "description": "Contains information about the proof",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Defines the proof type",
                    "type": "string"
                },
                "proofPurpose": {
                    "description": "Defines the purpose of the proof",
                    "type": "string"
                },
                "created": {
                    "description": "Defines the date and time, when the proof has been created",
                    "type": "string",
                    "format": "date-time"
                },
                "verificationMethod": {
                    "description": "Contains information about the verification method / proof mechanisms",
                    "type": "string"
                },
                "jws": {
                    "description": "Defines the proof value in JWS format",
                    "type": "string"
                }
            },
            "required": [
                "type",
                "proofPurpose",
                "created",
                "verificationMethod",
                "jws"
            ]
        }
    },
    "required": [
        "@context",
        "id",
        "type",
        "issuer",
        "issuanceDate",
        "issued",
        "validFrom",
        "credentialSubject",
        "credentialSchema"
    ]
}

=== walt-id/waltid-ssikit/src/main/resources/vc-templates/EbsiVerifiableAttestationLegal.json
{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https:/.europa.eu/schemas/v-id/2020/v1",
        "https:/.europa.eu/schemas/eidas/2020/v1"
    ],
    "id": "urn:did:123456",
    "type": ["VerifiableCredential", "VerifiableAttestation"],
    "issuer": "did:ebsi:2757945549477fc571663bee12042873fe555b674bd294a3",
    "issuanceDate": "2019-06-22T14:11:44Z",
    "validFrom": "2019-06-22T14:11:44Z",
    "issued": "2019-06-22T14:11:44Z",
    "credentialSubject": {
        "id": "did:ebsi:2659b154a445434a39d91149ead3bd993cb99fd5e78281b7",
        "identifier": [
            {
                "schemeID": "SHACL",
                "value": "SHACL ID 1",
                "id": "http://student.id/41231232"
            }
        ],
        "legalName": "Example Company"
    },
    "credentialStatus": {
        "id": "https:/europa.eu/status/identity#1dee355d-0432-4910-ac9c-70d89e8d674e",
        "type": "CredentialStatusList2020"
    },
    "credentialSchema": {
        "id": "https:/.europa.eu/tsr-vid/verifiableid1.json",
        "type": "FullJsonSchemaValidator2021"
    },
    "evidence": [
        {
            "id": "https:/.europa.eu/tsr-vid/evidence/f2aeec97-fc0d-42bf-8ca7-0548192d4231",
            "type": ["DocumentVerification"],
            "verifier": "did:ebsi:2e81454f76775c687694ee6772a17796436768a30e289555",
            "evidenceDocument": ["Passport"],
            "subjectPresence": "Physical",
            "documentPresence": ["Physical"]
        }
    ],
    "proof": {
        "type": "EidasSeal2021",
        "created": "2019-06-22T14:11:44Z",
        "proofPurpose": "assertionMethod",
        "verificationMethod": "did:ebsi:2757945549477fc571663bee12042873fe555b674bd294a3#2368332668",
        "jws": "HG21J4fdlnBvBA+y6D...amP7O="
    }
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-muti-uni-pilot/verifiable-diploma/2022-11/examples/digicomp-generic.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "type": ["VerifiableCredential", "VerifiableAttestation", "Europass"],
  "id": "urn:credential:5a4d5412-27e3-4540-a5e5-f1aa4d55b20c",
  "issuer": "did:epass:org:1",
  "issuanceDate": "2020-07-20T13:58:53+02:00",
  "issued": "2020-07-20T13:58:53+02:00",
  "validFrom": "2019-09-20T00:00:00+02:00",
  "credentialSubject": {
    "id": "did:epass:person:1",
    "identifier": {
      "schemeID": "Student identification number",
      "value": 99009900
    },
    "achieved": [
      {
        "id": "urn:epass:learningAchievement:1",
        "title": "TITLE OF PROGRAMME",
        "wasDerivedFrom": [
          {
            "id": "urn:epass:assessment:1",
            "title": "Overall Diploma Assessment",
            "grade": "excellent (5)"
          }
        ],
        "specifiedBy": [
          {
            "id": "urn:epass:qualification:1",
            "title": "Title of Achievement",
            "eqfLevel": "http://data.europa.eu/snb/eqf/5",
            "learningOutcome": [
              {
                "name": "Outcome1",
                "id": "urn:epass:learningOutcome:1",
                "title": "Name of DigiComp Competence",
                "description": "Description of DigiCompCompetence",
                "relatedSkill": ["http://data.europa.eu/snb/dcf/860966ekgo"]
              },
              {
                "name": "Outcome2",
                "id": "urn:epass:learningOutcome:2",
                "title": "Name of DigiComp Competence 2",
                "description": "Description of DigiCompCompetence 2",
                "relatedSkill": ["http://data.europa.eu/snb/dcf/34v10n662m"]
              }
            ]
          }
        ],
        "hasPart": {
          "learningAchievements": [
            {
              "id": "urn:epass:learningAchievement:3",
              "title": "Topic #1",
              "specifiedBy": [
                {
                  "id": "urn:epass:qualification:3",
                  "title": "Topic #1",
                  "learningOutcome": [
                    {
                      "name": "LO1",
                      "id": "urn:epass:learningOutcome:1",
                      "title": "Name of DigiComp Competence",
                      "description": "Description of DigiCompCompetence",
                      "relatedSkill": [
                        "http://data.europa.eu/snb/dcf/860966ekgo"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "id": "urn:epass:learningAchievement:3",
              "title": "Topic #1",
              "specifiedBy": [
                {
                  "id": "urn:epass:qualification:3",
                  "title": "Topic #1",
                  "learningOutcome": [
                    {
                      "name": "LO3",
                      "id": "urn:epass:learningOutcome:1",
                      "title": "Name of DigiComp Competence",
                      "description": "Description of DigiCompCompetence",
                      "relatedSkill": [
                        "http://data.europa.eu/snb/dcf/860966ekgo"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    ]
  },
  "credentialStatus": {
    "id": "https://uri.to.status",
    "type": "TrustedCredentialStatus2021"
  },
  "credentialSchema": {
    "type": "FullJsonSchemaValidator2021",
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x6b304591b86b7e5e4c8a713ddfb84ee5810a56334827adda4e741f80b9aa49ed"
  }
}
