=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-attestation/2022-11/schame-online.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "EBSI Verifiable Attestation",
    "description": "Schema of an EBSI Verifiable Attestation",
    "type": "object",
    "properties": {
        "@context": {
            "description": "Defines semantic context of the Verifiable Attestation",
            "type": "array",
            "items": {
                "type": "string",
                "format": "uri"
            }
        },
        "id": {
            "description": "Defines unique identifier of the Verifiable Attestation",
            "type": "string",
            "format": "uri"
        },
        "type": {
            "description": "Defines the Verifiable Credential type",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "issuer": {
            "description": "Defines the issuer of the Verifiable Attestation",
            "type": "string",
            "format": "uri"
        },
        "issuanceDate": {
            "description": "Defines the date and time, when the Verifiable Attestation becomes valid",
            "type": "string",
            "format": "date-time"
        },
        "issued": {
            "description": "Defines when the Verifiable Attestation was issued",
            "type": "string",
            "format": "date-time"
        },
        "validFrom": {
            "description": "Defines the date and time, when the Verifiable Attestation becomes valid",
            "type": "string",
            "format": "date-time"
        },
        "validUntil": {
            "description": "Defines the date and time, when the Verifiable Attestation expires",
            "type": "string",
            "format": "date-time"
        },
        "expirationDate": {
            "description": "Defines the date and time, when the Verifiable Attestation expires",
            "type": "string",
            "format": "date-time"
        },
        "credentialSubject": {
            "description": "Defines information about the subject that is described by the Verifiable Attestation",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Defines the DID of the subject that is described by the Verifiable Attestation",
                    "type": "string",
                    "format": "uri"
                }
            }
        },
        "credentialStatus": {
            "description": "Contains information about how to verify the status of the Verifiable Attestation (via the Revocation and Endorsement Registry, RER)",
            "type": "object",
            "properties": {
                "id": {
                    "description": "References record in the Revocation and Endorsement Registry (RER) to enable verification of a Verifiable Attestationâ€™s validity",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines the Verifiable Credential status type",
                    "type": "string"
                },
                "statusPurpose": {
                    "description": "Purpose of the status entry",
                    "type": "string",
                    "enum": [
                        "revocation",
                        "suspension"
                    ]
                },
                "statusListIndex": {
                    "description": "Integer expressed as a string. The zero based index value identifies the bit position of the status",
                    "type": "string"
                },
                "statusListCredential": {
                    "description": "URL referencing the StatusList2021Credential",
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": [
                "id",
                "type"
            ]
        },
        "credentialSchema": {
            "description": "Contains information about the credential schema (template) on which the Verifiable Authorisation is based",
            "type": "object",
            "properties": {
                "id": {
                    "description": "References the credential schema (template) stored on the (relevant) Trusted Schemas Registry (TSR) on which the Verifiable Authorisation is based",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines credential schema type",
                    "type": "string",
                    "enum": [
                        "FullJsonSchemaValidator2021"
                    ]
                }
            },
            "required": [
                "id",
                "type"
            ]
        },
        "evidence": {
            "description": "Contains information about the process which resulted in the issuance of the Verifiable Attestation",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
                        "type": "string"
                    },
                    "type": {
                        "description": "Defines the evidence type",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "id",
                    "type"
                ]
            }
        },
        "proof": {
            "description": "Contains information about the proof",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Defines the proof type",
                    "type": "string"
                },
                "proofPurpose": {
                    "description": "Defines the purpose of the proof",
                    "type": "string"
                },
                "created": {
                    "description": "Defines the date and time, when the proof has been created",
                    "type": "string",
                    "format": "date-time"
                },
                "verificationMethod": {
                    "description": "Contains information about the verification method / proof mechanisms",
                    "type": "string"
                },
                "jws": {
                    "description": "Defines the proof value in JWS format",
                    "type": "string"
                }
            },
            "required": [
                "type",
                "proofPurpose",
                "created",
                "verificationMethod",
                "jws"
            ]
        }
    },
    "required": [
        "@context",
        "id",
        "type",
        "issuer",
        "issuanceDate",
        "issued",
        "validFrom",
        "credentialSubject",
        "credentialSchema"
    ]
}

=== walt-id/waltid-ssikit/src/test/resources/vc-templates/EbsiDiplomaVerifiableAccreditation.json
{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://essif.europa.eu/schemas/vc/2020/v1"
    ],
    "id": "https://essif.europa.eu/tsr/53",
    "type": [
        "VerifiableCredential",
        "VerifiableAttestation",
        "VerifiableAccreditation",
        "DiplomaVerifiableAccreditation"
    ],
    "issuer": "did:ebsi:00001234",
    "issuanceDate": "2020-06-22T14:11:44Z",
    "issued": "2020-06-22T14:11:44Z",
    "credentialSubject": {
        "id": "did:ebsi:00001235",
        "authorizationClaims": {
            "accreditationType": "http://data.europa.eu/snb/accreditation/003293d2ce",
            "decision": "fully compliant",
            "report": ["https://www.example.com/URLtoreport.pdf"],
            "limitQFLevel": [
                "http://data.europa.eu/snb/eqf/6",
                "http://data.europa.eu/snb/eqf/7"
            ],
            "limitField": ["http://data.europa.eu/snb/isced-f/0419"],
            "limitJurisdiction": [
                "http://publications.europa.eu/resource/authority/atu/NLD"
            ],
            "reviewDate": "2024-04-22T14:11:44Z"
        }
    },
    "expirationDate": "2024-06-22T14:11:44Z",
    "validFrom": "2021-11-01T00:00:00Z",
    "credentialStatus": {
        "id": "https://essif.europa.eu/status/45",
        "type": "CredentialsStatusList2020"
    },
    "credentialSchema": {
        "id": "https://essif.europa.eu/tsr-123/verifiableattestation.json",
        "type": "FullJsonSchemaValidator2021"
    },
    "proof": {
        "type": "EidasSeal2019",
        "created": "2019-06-22T14:11:44Z",
        "proofPurpose": "assertionMethod",
        "verificationMethod": "http://uri-to-verification-method",
        "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X",
        "proofValue": "BD21J4fdlnBvBA+y6D...fnC8Y="
    }
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-muti-uni-pilot/verifiable-attestation-organisational-id/2022-11/examples/Bengales_organizationVerifiableAttestation.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://europa.eu/schemas/v-id/2020/v1",
    "https://europa.eu/schemas/eidas/2020/v1"
  ],
  "id": "urn:uuid:1dee355d-0432-4910-ac9c-70d89e8d674e",
  "type": ["VerifiableCredential", "VerifiableAttestation"],
  "issuer": "did:ebsi:2757945549477fc571663bee12042873fe555b674bd294a3",
  "issuanceDate": "2019-03-22T14:11:44Z",
  "issued": "2019-03-22T14:11:44Z",
  "validFrom": "2019-03-22T14:11:44Z",
  "credentialSubject": {
    "id": "did:ebsi:2659b154a445434a39d91149ead3bd993cb99fd5e78281b7",
    "legalName": "Berlin Charlottenburg High School"
  },
  "credentialStatus": {
    "id": "https://europa.eu/status/identity#verifiableID-1dee355d-0432-4910-ac9c-70d89e8d674e",
    "type": "CredentialStatusList2020"
  },
  "credentialSchema": {
    "id": "https://europa.eu/tsr-vid/verifiableid1.json",
    "type": "FullJsonSchemaValidator2021"
  },
  "evidence": [
    {
      "id": "https:/.europa.eu/tsr-vid/evidence/f2aeec97-fc0d-42bf-8ca7-0548192d4231",
      "type": ["DocumentVerification"],
      "verifier": "did:ebsi:2e81454f76775c687694ee6772a17796436768a30e289555",
      "evidenceDocument": ["Passport"],
      "subjectPresence": "Physical",
      "documentPresence": ["Physical"]
    }
  ]
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-muti-uni-pilot/verifiable-diploma/2022-11/examples/Microcredential_finetuned.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://base.uri.europass/contexts/v1"
  ],
  "type": ["VerifiableCredential", "VerifiableAttestation", "Europass"],
  "id": "urn:credential:5a4d5412-27e3-4540-a5e5-f1aa4d55b20c",
  "issuer": "did:epass:org:1",
  "issuanceDate": "2020-07-20T13:58:53+02:00",
  "issued": "2020-07-20T13:58:53+02:00",
  "validFrom": "2019-09-20T00:00:00+02:00",
  "credentialSubject": {
    "id": "did:epass:person:1",
    "identifier": [
      {
        "schemeID": "Student identification number",
        "value": 99009900
      }
    ],
    "achieved": [
      {
        "id": "urn:epass:learningAchievement:1",
        "title": "Data and software business",
        "wasDerivedFrom": [
          {
            "id": "urn:epass:assessment:1",
            "title": "Overall grade",
            "grade": "excellent (5)",
            "specifiedBy": {
              "id": "urn:epass:asssessmentspec:1",
              "title": "Overall grade",
              "gradingScheme": {
                "id": "urn:epass:scoringschemespec:1",
                "title": "General grading scheme in Finland",
                "definition": "The Finnish national grading scheme consists of five grades with numerical equivalents: 5 (outstanding); 4 (very good); 3 (good); 2 (sufficient); 1 (insufficient - fail). The minimum passing grade is 2."
              }
            },
            "hasPart": [
              {
                "id": "urn:epass:assessment:2",
                "title": "individual assignment 1",
                "grade": "excellent (5)",
                "specifiedBy": {
                  "id": "urn:epass:asssessmentspec:2",
                  "title": "individual assignment 1",
                  "gradingScheme": {
                    "id": "urn:epass:scoringschemespec:2",
                    "title": "General grading scheme in Finland",
                    "definition": "The Finnish national grading scheme consists of five grades with numerical equivalents: 5 (outstanding); 4 (very good); 3 (good); 2 (sufficient); 1 (insufficient - fail). The minimum passing grade is 2."
                  }
                }
              },
              {
                "id": "urn:epass:assessment:3",
                "title": "individual assignment 2",
                "grade": "excellent (5)",
                "specifiedBy": {
                  "id": "urn:epass:asssessmentspec:3",
                  "title": "individual assignment 2",
                  "gradingScheme": {
                    "id": "urn:epass:scoringschemespec:3",
                    "title": "General grading scheme in Finland",
                    "definition": "The Finnish national grading scheme consists of five grades with numerical equivalents: 5 (outstanding); 4 (very good); 3 (good); 2 (sufficient); 1 (insufficient - fail). The minimum passing grade is 2."
                  }
                }
              },
              {
                "id": "urn:epass:assessment:4",
                "title": "Project assignment",
                "grade": "excellent (5)",
                "specifiedBy": {
                  "id": "urn:epass:asssessmentspec:4",
                  "title": "Project assignment",
                  "gradingScheme": {
                    "id": "urn:epass:scoringschemespec:4",
                    "title": "General grading scheme in Finland",
                    "definition": "The Finnish national grading scheme consists of five grades with numerical equivalents: 5 (outstanding); 4 (very good); 3 (good); 2 (sufficient); 1 (insufficient - fail). The minimum passing grade is 2."
                  }
                }
              }
            ]
          }
        ],
        "specifiedBy": [
          {
            "id": "urn:epass:learningSpecification:1",
            "title": "Data and Software Business",
            "Definition": "formal learning",
            "hasECTSCreditPoints": "5",
            "learningSetting": "http://data.europa.eu/snb/learning-setting/6fd4685715",
            "learningOutcomes": [
              {
                "id": "urn:epass:learningOutcome:1",
                "name": "Basic principles of data and software business",
                "definition": "Student understands the basic principles of data and software business, and the special characteristics of software industry",
                "relatedESCOSkill": [
                  "http://data.europa.eu/esco/skill/943d07ec-fb75-4bb5-bc07-20451a2b66e4",
                  "http://data.europa.eu/esco/skill/7dd94ad3-13d6-43fe-8b94-51fcbf67ced9",
                  "http://data.europa.eu/esco/skill/fcb2b5f4-3a64-42f2-987a-073bea986104"
                ]
              },
              {
                "id": "urn:epass:learningOutcome:2",
                "name": "Monetizing with data and software",
                "definition": "He/she can critically analyse how it is possible to monetize with data and software",
                "relatedESCOSkill": [
                  "http://data.europa.eu/esco/skill/c624c6a3-b0ba-4a31-a296-0d433fe47e41"
                ]
              },
              {
                "id": "urn:epass:learningOutcome:3",
                "name": "Collaboratively develop a data or software concept",
                "definition": "He/she can analyze the feasibility of software business models. Student can apply theoretical knowledge and understanding of the data and software business characteristics to collaboratively create a solid lean canvas model for a software start-up.",
                "relatedESCOSkill": [
                  "http://data.europa.eu/esco/skill/60c78287-22eb-4103-9c8c-28deaa460da0",
                  "http://data.europa.eu/esco/skill/09e28145-e205-4b7a-8b3b-5c4876396069",
                  "http://data.europa.eu/esco/skill/27ed854c-15b8-4ba2-90e9-ae888a219703"
                ]
              }
            ]
          }
        ]
      }
    ],
    "wasInfluencedBy": [
      {
        "id": "urn:epass:activity:1",
        "identifier": [
          {
            "schemeID": "Activity ID",
            "value": "GAB701"
          }
        ],
        "title": "Individual exercise",
        "Description": "The individual exercise is a written task that has two parts: 1. Choose 1 main lecture topic to focus on 2. Choose 2 guest lectures to focus on-Access the documentation in Moodle and answer the according questions in your own time (by the 5th of October) -Each task requires some self-learning, such as finding suitable examples for typical revenue streams and so on. -Return your answers in one document and upload to Moodle (note. Plagiarism tested automatically). The individual assignment accounts for 40% of the final grade.",
        "specifiedBy": {
          "id": "urn:epass:learningactivityspec:1",
          "title": "Individual exercise",
          "learningActivityType": [
            "http://data.europa.eu/snb/learning-activity/bf2e3a7bae"
          ],
          "language": [
            "http://publications.europa.eu/resource/authority/language/ENG"
          ]
        }
      },
      {
        "id": "urn:epass:activity:2",
        "identifier": [
          {
            "schemeID": "Activity ID",
            "value": "GAE701"
          }
        ],
        "title": "Course exercise",
        "Description": "Minimum viable product (MVP) Concept to explore product-market fit. Students will Identify the topic area of their MVP (Data-, platform-, product-Or service business), sketch their MVP (Use lean business model canvas), present and then report on their MVP. 3-5 people, 4 weeks remote collaboration, pitching of MVPs in a final event together with Business Tampere and Start-up centre Tribe. The course exercise accounts for 60% of the final grade",
        "specifiedBy": {
          "id": "urn:epass:learningactivityspec:2",
          "title": "Group exercise",
          "learningActivityType": [
            "http://data.europa.eu/snb/learning-activity/bf2e3a7bae"
          ],
          "language": [
            "http://publications.europa.eu/resource/authority/language/ENG"
          ]
        }
      },
      {
        "id": "urn:epass:activity:3",
        "identifier": [
          {
            "schemeID": "Activity ID",
            "value": "GAO701"
          }
        ],
        "title": "Zoom lecture",
        "Description": "includes both basic lectures on data and software business and guest lectures by companies.",
        "specifiedBy": {
          "id": "urn:epass:learningactivityspec:3",
          "title": "Zoom lectures",
          "learningActivityType": [
            "http://data.europa.eu/snb/learning-activity/bf2e3a7bae"
          ],
          "language": [
            "http://publications.europa.eu/resource/authority/language/ENG"
          ]
        }
      }
    ]
  },
  "credentialStatus": {
    "id": "https://uri.to.status",
    "type": "TrustedCredentialStatus2021"
  },
  "credentialSchema": {
    "id": "https://uri.to.schema",
    "type": "FullJsonSchemaValidator2021"
  }
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-muti-uni-pilot/verifiable-diploma/2022-11/examples/diploma-rntuo-credential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://essif.europa.eu/schemas/vc/2020/v1"
  ],
  "type": ["VerifiableCredential", "VerifiableAttestation", "Europass"],
  "expirationDate": "2023-03-04T14:50:55Z",
  "id": "urn:credential:rntuo:908ae789-2b27-44f6-b62e-b2fc0ab4e886",
  "issued": "2022-03-04T14:50:55Z",
  "issuer": "did:ebsi:zjAmQ2qyJvZ7sLXWhdtDF8K",
  "validFrom": "2022-03-04T14:50:55Z",
  "issuanceDate": "2022-03-04T14:50:55Z",
  "credentialSubject": {
    "achieved": [
      {
        "id": "urn:epass:learningAchievement:1",
        "identifier": [
          {
            "schemeID": "RNTUO Certificate ID",
            "value": "2020016696"
          }
        ],
        "specifiedBy": [
          {
            "id": "urn:epass:qualification:1",
            "eqflLevel": "http://data.europa.eu/snb/eqf/7",
            "title": "Máster Universitario en Asuntos Internacionales: Economía, Política y Derecho por la Universidad Pontificia Comillas"
          }
        ],
        "title": "Máster Universitario en Asuntos Internacionales: Economía, Política y Derecho por la Universidad Pontificia Comillas",
        "wasAwardedBy": {
          "awardingBody": [
            "Universidad Pontificia Comillas (Universidad de la Iglesia Católica)"
          ],
          "awardingDate": "2019-09-11T00:00:00Z",
          "awardingLocation": ["https://essif.europa.eu/madrid"],
          "id": "urn:epass:awardingProcess:1"
        }
      }
    ],
    "id": "did:ebsi:zrn14Vr8Uuz54iAiUpfgyJS"
  },
  "credentialStatus": {
    "id": "https://essif.europa.eu/status/43",
    "type": "CredentialsStatusList2020"
  },
  "credentialSchema": {
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x928c0ebb5cfc72c70e1273812eb16f67fa492c52ac9c6330f5e94374d2f48502",
    "type": "FullJsonSchemaValidator2021"
  }
}

=== walt-id/waltid-ssikit/src/main/resources/vc-templates/StudentId.json
{
    "@context": ["https://www.w3.org/2018/credentials/v1"],
    "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
    "type": ["VerifiableCredential", "VerifiableAttestation", "StudentId"],
    "issuer": "did:ebsi:00001234",
    "issuanceDate": "2021-11-01T00:00:00Z",
    "validFrom": "2021-11-01T00:00:00Z",
    "expirationDate": "2024-06-22T14:11:44Z",
    "issued": "2020-06-22T14:11:44Z",
    "credentialSubject": {
        "id": "did:ebsi:00001235",
        "personalIdentifier": "123456"
    },
    "credentialSchema": {
        "id": "https://api-pilot.ebsi.eu/trusted-schemas-registry/v1/schemas/0x6ff8cdf21b3969222e4a799d9605997b0f1de7d49edcde4ad0c09eb636dfaf3c",
        "type": "FullJsonSchemaValidator2021"
    }
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-attestation/2022-11/examples/example.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd",
  "type": ["VerifiableCredential", "VerifiableAttestation"],
  "issuer": "did:ebsi:00001234",
  "issuanceDate": "2021-11-01T00:00:00Z",
  "validFrom": "2021-11-01T00:00:00Z",
  "expirationDate": "2024-06-22T14:11:44Z",
  "issued": "2020-06-22T14:11:44Z",
  "credentialSubject": {
    "id": "did:ebsi:00001235"
  },
  "credentialStatus": {
    "id": "https://api-test.ebsi.eu/trusted-issuers-registry/v3/issuers/did:ebsi:zyrMG8T9xYbNoSwyQa4SGMJ/proxy/6cc5fcc621d8098977d378ec7bf63f9ad0b204d56bb604f75bc9290e7033ac84/credentials/status/5#129430",
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": "129430",
    "statusListCredential": "https://api-test.ebsi.eu/trusted-issuers-registry/v3/issuers/did:ebsi:zyrMG8T9xYbNoSwyQa4SGMJ/proxy/6cc5fcc621d8098977d378ec7bf63f9ad0b204d56bb604f75bc9290e7033ac84/credentials/status/5"
  },
  "credentialSchema": {
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0xf30fd418c8b2c1534b0685e12b044d3d29284fe37762a45d0c1e5601eed3d1d9",
    "type": "FullJsonSchemaValidator2021"
  }
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-muti-uni-pilot/verifiable-diploma/2022-11/examples/EnglishSample.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://base.uri.europass/contexts/v1"
  ],
  "type": ["VerifiableCredential", "VerifiableAttestation", "Europass"],
  "id": "urn:credential:5a4d5412-27e3-4540-a5e5-f1aa4d55b20c",
  "issuer": "did:epass:org:1",
  "issuanceDate": "2020-07-20T13:58:53+02:00",
  "issued": "2020-07-20T13:58:53+02:00",
  "validFrom": "2019-09-20T00:00:00+02:00",
  "credentialSubject": {
    "id": "did:epass:person:1",
    "achieved": [
      {
        "id": "urn:epass:learningAchievement:1",
        "identifier": [
          {
            "schemeID": "University Record Identifier",
            "value": "123456"
          }
        ],
        "title": "TITLE OF PROGRAMME",
        "specifiedBy": [
          {
            "id": "urn:epass:qualification:1",
            "title": "Title of Achievement"
          }
        ],
        "wasInfluencedBy": [
          {
            "id": "urn:epass:activity:1",
            "title": "Coursework",
            "startedAtTime": "2022-03-04T14:50:55Z",
            "endedAtTime": "2022-03-04T14:50:55Z"
          }
        ]
      }
    ]
  },
  "credentialStatus": {
    "id": "https://essif.europa.eu/status/43",
    "type": "CredentialsStatusList2020"
  },
  "credentialSchema": {
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x928c0ebb5cfc72c70e1273812eb16f67fa492c52ac9c6330f5e94374d2f48502",
    "type": "FullJsonSchemaValidator2021"
  }
}

=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-muti-uni-pilot/education-verifiable-accreditation-records/2022-11/examples/programmeAccreditation_example.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://essif.europa.eu/schemas/vc/2020/v1"
  ],
  "id": "https://essif.europa.eu/tsr/53",
  "type": [
    "VerifiableCredential",
    "VerifiableAttestation",
    "VerifiableAccreditation",
    "DiplomaVerifiableAccreditation"
  ],
  "issuer": "did:ebsi:00001234",
  "issued": "2020-06-22T14:11:44Z",
  "issuanceDate": "2021-11-01T00:00:00Z",
  "validFrom": "2021-11-01T00:00:00Z",
  "expirationDate": "2024-06-22T14:11:44Z",
  "credentialSubject": {
    "id": "did:ebsi:00001235",
    "authorizationClaims": {
      "accreditationType": "http://data.europa.eu/snb/accreditation/e57dddfcf3",
      "decision": "fully compliant",
      "report": ["https://www.example.com/URLtoreport.pdf"],
      "limitQualification": [
        {
          "id": "http://qualdb.org/qual/1",
          "title": "Masters' Diploma in Sociology",
          "alternativeLabel": [
            "Diploma in Sociology",
            "Masters' Diploma in Sociological Studies"
          ],
          "EQFLevel": "http://data.europa.eu/snb/eqf/6",
          "NQFLevel": "http://data.europa.eu/snb/qdr/c_1711a061"
        }
      ],
      "limitJurisdiction": [
        "http://publications.europa.eu/resource/authority/atu/NLD"
      ],
      "reviewDate": "2024-04-22T14:11:44Z"
    }
  },
  "credentialStatus": {
    "id": "https://essif.europa.eu/status/45",
    "type": "CredentialsStatusList2020"
  },
  "credentialSchema": {
    "id": "https://essif.europa.eu/tsr-123/verifiableattestation.json",
    "type": "FullJsonSchemaValidator2021"
  },
  "proof": {
    "type": "EidasSeal2019",
    "created": "2019-06-22T14:11:44Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "http://uri-to-verification-method",
    "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X",
    "proofValue": "BD21J4fdlnBvBA+y6D...fnC8Y="
  }
}
