=== walt-id/waltid-ssikit/src/test/resources/schemas/NEOM/StudentCard.json
{
    "$schema" : "http://json-schema.org/draft-07/schema#",
    "type" : "object",
    "properties" : {
        "@context" : {
            "type" : "array",
            "items" : {
                "type" : "string"
            }
        },
        "credentialSchema" : {
            "type" : "object",
            "properties" : {
                "id" : {
                    "type" : "string"
                },
                "type" : {
                    "type" : "string"
                }
            },
            "additionalProperties" : false
        },
        "credentialStatus" : {
            "type" : "object",
            "properties" : {
                "id" : {
                    "type" : "string"
                },
                "type" : {
                    "type" : "string"
                }
            },
            "additionalProperties" : false
        },
        "credentialSubject" : {
            "type" : "object",
            "properties" : {
                "currentAddress" : {
                    "type" : "array",
                    "items" : {
                        "type" : "string"
                    }
                },
                "dateOfBirth" : {
                    "type" : "string"
                },
                "familyName" : {
                    "type" : "string"
                },
                "firstName" : {
                    "type" : "string"
                },
                "gender" : {
                    "type" : "string"
                },
                "id" : {
                    "type" : "string"
                },
                "identifier" : {
                    "type" : "array",
                    "items" : {
                        "type" : "object",
                        "properties" : {
                            "schemeID" : {
                                "type" : "string"
                            },
                            "value" : {
                                "type" : "string"
                            }
                        },
                        "additionalProperties" : false
                    }
                },
                "nameAndFamilyNameAtBirth" : {
                    "type" : "string"
                },
                "matriculationNumber" : {
                    "type" : "string"
                },
                "placeOfBirth" : {
                    "type" : "string"
                }
            },
            "additionalProperties" : false
        },
        "evidence" : {
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties" : {
                    "documentPresence" : {
                        "type" : "array",
                        "items" : {
                            "type" : "string"
                        }
                    },
                    "evidenceDocument" : {
                        "type" : "array",
                        "items" : {
                            "type" : "string"
                        }
                    },
                    "id" : {
                        "type" : "string"
                    },
                    "subjectPresence" : {
                        "type" : "string"
                    },
                    "type" : {
                        "type" : "array",
                        "items" : {
                            "type" : "string"
                        }
                    },
                    "verifier" : {
                        "type" : "string"
                    }
                },
                "additionalProperties" : false
            }
        },
        "expirationDate" : {
            "type" : "string"
        },
        "id" : {
            "type" : "string"
        },
        "issuanceDate" : {
            "type" : "string"
        },
        "issued" : {
            "type" : "string"
        },
        "issuer" : {
            "type" : "string"
        },
        "proof" : {
            "type" : "object",
            "properties" : {
                "created" : {
                    "type" : "string"
                },
                "creator" : {
                    "type" : "string"
                },
                "domain" : {
                    "type" : "string"
                },
                "jws" : {
                    "type" : "string"
                },
                "nonce" : {
                    "type" : "string"
                },
                "proofPurpose" : {
                    "type" : "string"
                },
                "type" : {
                    "type" : "string"
                },
                "verificationMethod" : {
                    "type" : "string"
                }
            },
            "additionalProperties" : false
        },
        "type" : {
            "type" : "array",
            "items" : {
                "type" : "string"
            }
        },
        "validFrom" : {
            "type" : "string"
        }
    },
    "required" : [ "@context", "type" ],
    "title" : "EBSI Natural Person Verifiable ID",
    "description" : "Schema of an EBSI Verifiable ID for a natural person",
    "additionalProperties" : false
}

=== walt-id/waltid-ssikit/src/test/resources/verifiable-credentials/vc-ebsi-verifiable-authorisation.json
{
  "id": "vc:ebsi:authentication#6c4b5d20-1791-46b3-a1ed-6d384e4c5f25",
  "issuer": "did:ebsi:4jPxcigvfifZyVwym5zjxaKXGJTt7YwFtpg6AXtsR4d5",
  "validFrom": "2021-05-31T12:29:47Z",
  "credentialSubject": {
    "id": "did:ebsi:2LEi74mCZpgC8EqcngLCzUCL5d8W3dxfdjiy9XhaVoDyi259"
  },
  "credentialSchema": {
    "id": "https://api.preprod.ebsi.eu/trusted-schemas-registry/v1/schemas/0x312e332e362e312e342e312e313636342e31302e3138372e312e322e322e3333",
    "type": "OID"
  },
  "issuanceDate": "2021-05-31T12:29:47Z",
  "expirationDate": "2021-11-29T12:29:47Z",
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1",
    "https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json"
  ],
  "type": [
    "VerifiableCredential",
    "VerifiableAuthorisation"
  ],
  "proof": {
    "type": "EcdsaSecp256k1Signature2019",
    "created": "2021-05-31T12:29:47Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:ebsi:4jPxcigvfifZyVwym5zjxaKXGJTt7YwFtpg6AXtsR4d5#keys-1",
    "jws": "eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ..UhwM1AYmCYKtuNAShubnzxeBoOWR8bS1FZpIp958DA6WRp_thPtaEOKPkksRKswgg1UYNWbJRBVPEXQKQloD0w"
  }
}
