=== walt-id/waltid-ssikit/src/test/resources/ebsi-json-schema/ebsi-attestation/2022-11_01/schema-online.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "EBSI Verifiable Attestation",
    "description": "Defines generic structure for any EBSI related Verifiable Credential",
    "type": "object",
    "properties": {
        "@context": {
            "description": "Semantic context for the issued credential",
            "type": "array",
            "items": {
                "type": "string",
                "format": "uri"
            }
        },
        "id": {
            "description": "Globally unique identifier for the issued credential",
            "type": "string",
            "format": "uri"
        },
        "type": {
            "description": "Full type chain, used to identify the credential base types",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "issuer": {
            "description": "DID which issued this credential",
            "type": "string",
            "format": "uri"
        },
        "issuanceDate": {
            "description": "Defines the date and time, when the issued credential becomes valid",
            "type": "string",
            "format": "date-time"
        },
        "issued": {
            "description": "Defines when the issued credential was issued",
            "type": "string",
            "format": "date-time"
        },
        "validFrom": {
            "description": "Defines the date and time, when the issued credential becomes valid",
            "type": "string",
            "format": "date-time"
        },
        "validUntil": {
            "description": "Defines the date and time, when the issued credential expires",
            "type": "string",
            "format": "date-time"
        },
        "expirationDate": {
            "description": "Defines the date and time, when the issued credential expires",
            "type": "string",
            "format": "date-time"
        },
        "credentialSubject": {
            "description": "Defines information about the subject that is defined by the type chain",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Defines the DID of the subject that is described by the issued credential",
                    "type": "string",
                    "format": "uri"
                }
            }
        },
        "credentialStatus": {
            "description": "Defines revocation details for the issued credential. Further redefined by type extension",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Exact identity for the credential status",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines the revocation type extension",
                    "type": "string"
                }
            },
            "required": [
                "id",
                "type"
            ]
        },
        "credentialSchema": {
            "anyOf": [
                {
                    "$ref": "#/$defs/credentialSchema"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/credentialSchema"
                    }
                }
            ]
        },
        "termsOfUse": {
            "anyOf": [
                {
                    "$ref": "#/$defs/termsOfUse"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/termsOfUse"
                    }
                }
            ]
        },
        "evidence": {
            "description": "Contains information about the process which resulted in the issuance of the credential",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "description": "If present, it MUST contain a URL that points to where more information about this instance of evidence can be found.",
                        "type": "string"
                    },
                    "type": {
                        "description": "Defines the evidence type extension",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "type"
                ]
            }
        },
        "proof": {
            "description": "Contains information about the proof",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Defines the proof type",
                    "type": "string"
                },
                "proofPurpose": {
                    "description": "Defines the purpose of the proof",
                    "type": "string"
                },
                "created": {
                    "description": "Defines the date and time, when the proof has been created",
                    "type": "string",
                    "format": "date-time"
                },
                "verificationMethod": {
                    "description": "Contains information about the verification method / proof mechanisms",
                    "type": "string"
                },
                "jws": {
                    "description": "Defines the proof value in JWS format",
                    "type": "string"
                }
            },
            "required": [
                "type",
                "proofPurpose",
                "created",
                "verificationMethod",
                "jws"
            ]
        }
    },
    "required": [
        "@context",
        "id",
        "type",
        "issuer",
        "issuanceDate",
        "issued",
        "validFrom",
        "credentialSubject",
        "credentialSchema"
    ],
    "$defs": {
        "credentialSchema": {
            "description": "Contains information about the credential schema on which the issued credential is based",
            "type": "object",
            "properties": {
                "id": {
                    "description": "References the credential schema stored on the Trusted Schemas Registry (TSR) on which the Verifiable Authorisation is based",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines credential schema type",
                    "type": "string",
                    "enum": [
                        "FullJsonSchemaValidator2021"
                    ]
                }
            },
            "required": [
                "id",
                "type"
            ]
        },
        "termsOfUse": {
            "description": "Contains the terms under which the issued credential was issued",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Contains a URL that points to where more information about this instance of terms of use can be found.",
                    "type": "string",
                    "format": "uri"
                },
                "type": {
                    "description": "Defines the type extension",
                    "type": "string"
                }
            },
            "required": [
                "type"
            ]
        }
    }
}

=== walt-id/waltid-ssikit/src/test/resources/vc-templates/EbsiVerifiableAccreditationToAccredit.json
{
    "@context": ["https://www.w3.org/2018/credentials/v1"],
    "id": "urn:uuid:8568b525-a24e-4bc0-9d97-6a8459ec0130",
    "type": [
        "VerifiableCredential",
        "VerifiableAttestation",
        "VerifiableAccreditation",
        "VerifiableAccreditationToAccredit"
    ],
    "issuer": "did:ebsi:00001234",
    "issuanceDate": "2021-11-01T00:00:00Z",
    "validFrom": "2021-11-01T00:00:00Z",
    "expirationDate": "2024-06-22T14:11:44Z",
    "issued": "2020-06-22T14:11:44Z",
    "credentialSubject": {
        "id": "did:ebsi:00001235",
        "accreditedFor": [
            {
                "schemaId": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x010110",
                "types": [
                    "VerifiableCredential",
                    "VerifiableAttestation",
                    "DiplomaCredential"
                ],
                "limitJurisdiction": "https://publications.europa.eu/resource/authority/atu/FIN"
            }
        ]
    },
    "termsOfUse": [
        {
            "id": "https://api-test.ebsi.eu/trusted-issuers-registry/../..xyz",
            "type": "IssuanceCertificate"
        }
    ],
    "credentialSchema":
    {
        "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x1d7146f8897aa6cd5c59321ea0756ec61277028e4a8b3c13ec1b310ec47e6495",
        "type": "FullJsonSchemaValidator2021"
    }
}

=== walt-id/waltid-ssikit/src/main/resources/vc-templates/VerifiableId.json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "credentialSchema": {
    "id": "https://api.preprod.ebsi.eu/trusted-schemas-registry/v1/schemas/0xb77f8516a965631b4f197ad54c65a9e2f9936ebfb76bae4906d33744dbcc60ba",
    "type": "FullJsonSchemaValidator2021"
  },
  "credentialSubject": {
    "currentAddress": ["1 Boulevard de la Libert√©, 59800 Lille"],
    "dateOfBirth": "1993-04-08",
    "familyName": "DOE",
    "firstName": "Jane",
    "gender": "FEMALE",
    "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
    "nameAndFamilyNameAtBirth": "Jane DOE",
    "personalIdentifier": "0904008084H",
    "placeOfBirth": "LILLE, FRANCE"
  },
  "evidence": [{
    "documentPresence": ["Physical"],
    "evidenceDocument": ["Passport"],
    "subjectPresence": "Physical",
    "type": ["DocumentVerification"],
    "verifier": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN"
  }],
  "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
  "issued": "2021-08-31T00:00:00Z",
  "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
  "validFrom": "2021-08-31T00:00:00Z",
  "issuanceDate": "2021-08-31T00:00:00Z",
  "type": ["VerifiableCredential", "VerifiableAttestation", "VerifiableId"]
}
